### ISSUE TITLE
X resources under a minute

### ISSUE THREAD

**Issue by Bassicaly** [therabidsquirel/The-Fallout-Shelter-FAQ#2]
This is in regard to bullit 8 of section 11.2

The trick with closing the game after harvesting and waiting till the next cycle is available does not work for me. I run the game on android and tried different ways of doing this but it seems like the the minute timer itself also keeps going and so negates this possibility...

**Comment by therabidsquirel** [comment]
Hmm... This is an old bit of info that a number of people said worked, though I don't think I've ever done it myself. Do you have any Mr. Handy that can collect while the game is closed? That might be the only way it works.

**Comment by Bassicaly** [comment]
Thnx for the reply.

I already fulfilled the object by building an extra diner and rushing both
of them. Just wanted to point out the possible discrepancy from my point of
view :)

Cheers,

Bas

**Comment by therabidsquirel** [comment]
Thanks for letting me know. For now I'll update it saying that a Mr. Handy is necessary to perform that trick.
